## Learn Pandas :-

In [1]:
import pandas as pd

In [41]:
# Pandas is an open-source Python library used for data analysis, data cleaning, and data manipulation. It provides powerful, flexible, and easy-to-use tools to work with structured data, especially in the form of:

# Tabular data (like Excel sheets or SQL tables)

# Labeled data (with rows and columns)

### Series :-

In [3]:
data = [10, 20, 30]
series = pd.Series(data, index=['a', 'b', 'c'])
print(series) # like one dimension labeled array

a    10
b    20
c    30
dtype: int64

### Dataframe and its Operation :-

In [4]:
# Dataframe :- each row and column labeled
# each row work as series 
# Data stores like SQL table or EXcelsheet
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A", "B", "C"], index = ["x","y","z"])

In [ ]:
df.head() # Shows first 5 Row Data

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
df.tail(1) # Last 5 rows By default

   A  B  C
z  7  8  9

In [9]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [5]:
df.index.tolist() # give Row Names

['x', 'y', 'z']

In [11]:
df.info() # give information

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [12]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique() #it returns count of unique value in Column

A    3
B    3
C    3
dtype: int64

In [ ]:
df.size # size of data

12

### Unique find :-

In [16]:
data = {'ColA': [1, 2, 2, 3, 1, None],
        'ColB': ['apple', 'banana', 'apple', 'orange', 'banana', 'grape']}
df = pd.DataFrame(data )

# Count unique values in each column (default behavior)
unique_counts_col = df.nunique()
print("Unique counts per column:\n", unique_counts_col)

# Count unique values in each row
unique_counts_row = df.nunique(axis=1)
print("\nUnique counts per row:\n", unique_counts_row)

# Count unique values including NaN
unique_counts_with_nan = df.nunique(dropna=False)
print("\nUnique counts per column (including NaN):\n", unique_counts_with_nan)

Unique counts per column:
 ColA    3
ColB    4
dtype: int64

Unique counts per row:
 0    2
1    2
2    2
3    2
4    2
5    1
dtype: int64

Unique counts per column (including NaN):
 ColA    4
ColB    4
dtype: int64

In [ ]:
df["A"].unique() # returns unique value of Column

array([1, 4, 7])

In [33]:
df.shape

(3, 3)

### Loading in Dataframes form Files :-

In [6]:
coffee = pd.read_csv('./data/coffee.csv')

In [24]:
results = pd.read_parquet('./data/results.parquet')
results.head()
bios = pd.read_csv('./data/bios.csv')

In [ ]:
import openpyxl
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name = 'results')

### Accessing Data with Pandas :-

In [7]:
coffee.sample(10) # Random rows not continuos
coffee.tail() # last 5 rows
coffee # All Data rows
coffee.head() # first 5 rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [16]:
coffee.loc[1:3, ["Coffee Type","Day"] ] # loc[rows,columns] 
# loc[1:3] then start & end both inclusive 
# only for rows
# for column we need "Name"
# change perticular value :-
coffee.loc[1,"Coffee Type"] = "Maxx"
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday        Maxx          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
coffee.iloc[0:5, [0,1]] 
# for column not need name
# column directly accessible with Index

         Day Coffee Type
0     Monday    Espresso
1     Monday        Maxx
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso

In [23]:
coffee.at[1, "Coffee Type"] #for perticular single value
coffee.iat[1,1] # column using index
coffee.sort_values('Units Sold')
coffee.sort_values('Units Sold', ascending=False) # decrease
coffee.sort_values(['Units Sold', 'Coffee Type'], ascending=[0,1]) # decrease

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday        Maxx          15

### Filtering Data :-

In [25]:
# bios.info()
bios.loc[bios['born_region'] == 'Gujarat']
bios[(bios['height_cm'] > 180) & (bios['born_country']=='IND')]
bios[bios['name'].str.contains('Panchal | Patel')]
# bios[bios['weight_kg'] > 170]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19798,19937,Mohan Patel,1952-11-11,Auckland,Auckland,NZL,New Zealand,170.0,64.0,NaN
19799,19938,Ramesh Patel,1953-09-12,Auckland,Auckland,NZL,New Zealand,176.0,70.0,NaN
19800,19939,Paresh Patel,1965-07-29,Auckland,Auckland,NZL,New Zealand,NaN,NaN,NaN
103119,104089,Sumeet Patel,1960-10-09,NaN,NaN,NaN,India,171.0,62.0,NaN
107896,109035,Mitesh Patel,1976-05-09,NaN,NaN,NaN,New Zealand,175.0,68.0,NaN
128158,130671,Alessandra Patelli,1991-11-17,Conegliano,Treviso,ITA,Italy,180.0,70.0,NaN
140240,143743,Maana Patel,2000-03-18,NaN,NaN,NaN,India,NaN,NaN,NaN

In [28]:
# bios[bios['born_country'].isin(["USA","IND"]) & (bios['name'].str.startswith('Martin'))]
bios[bios['born_city'] == 'Cleveland']
# bios.query('born_country == "IND"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
2764,2776,Forest Montgomery,1874-08-22,Cleveland,Ohio,USA,United States,NaN,NaN,1947-05-07
8570,8617,Carmen Barth,1912-09-13,Cleveland,Ohio,USA,United States,175.0,72.0,1985-09-17
8582,8629,Nate Brooks,1933-08-04,Cleveland,Ohio,USA,United States,NaN,NaN,2020-04-14
8660,8707,Ted Kara,1916-04-02,Cleveland,Ohio,USA,United States,NaN,NaN,1944-02-14
...,...,...,...,...,...,...,...,...,...,...
124317,126611,Bridget Franek,1987-11-08,Cleveland,Ohio,USA,United States,168.0,57.0,NaN
124323,126617,Matt McLean,1988-05-13,Cleveland,Ohio,USA,United States,198.0,100.0,NaN
124383,126682,Terrell Gausha,1987-09-09,Cleveland,Ohio,USA,United States,178.0,75.0,NaN
133365,136304,Jason Pryor,1987-09-26,Cleveland,Ohio,USA,United States,175.0,80.0,NaN
143717,147372,Delante Johnson,1998-08-13,Cleveland,Ohio,USA,United States,178.0,NaN,NaN

### Adding and Removing Columns :-

In [29]:
coffee_new = coffee.copy()
coffee_new['prize'] = 4.99
coffee_new.head()

         Day Coffee Type  Units Sold  prize
0     Monday    Espresso          25   4.99
1     Monday        Maxx          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [41]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [30]:
import numpy as np
coffee['prize'] = 4.99 # New Column Prize
coffee["new_prize"] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)
# np.where() -> create conditional Statement np.where(condition, True, False)
coffee.head()

         Day Coffee Type  Units Sold  prize  new_prize
0     Monday    Espresso          25   4.99       3.99
1     Monday        Maxx          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [31]:
# coffee.drop(columns=['prize'], inplace=True)
coffee = coffee.drop(columns='prize') # Drop = Delete Column
coffee.head()

         Day Coffee Type  Units Sold  new_prize
0     Monday    Espresso          25       3.99
1     Monday        Maxx          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

In [33]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_prize']
coffee.head()

         Day Coffee Type  Units Sold  new_prize  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday        Maxx          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

In [35]:
coffee = coffee.rename(columns={'new_prize': 'Price', 'revenue':'Revenue'})
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday        Maxx          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [3]:
bios_new = bios.copy()
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new['born_Year'] = bios_new['born_datetime'].dt.year
bios_new[['name','born_Year']]
bios_new[bios_new['born_Year'] > 2007]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_Year
137792,141168,Rayssa Leal,2008-01-04,Imperatriz,Maranhão,BRA,Brazil,147.0,35.0,NaN,2008-01-04,2008.0
139592,143068,Sky Brown,2008-07-07,Miyazaki,Miyazaki,JPN,Great Britain,NaN,NaN,NaN,2008-07-07,2008.0
140902,144431,Kokona Hiraki,2008-08-26,NaN,NaN,NaN,Japan,NaN,NaN,NaN,2008-08-26,2008.0
143149,146782,Hend Zaza,2009-01-01,Hama,Hama,SYR,Syrian Arab Republic,NaN,NaN,NaN,2009-01-01,2009.0

In [4]:
bios_new.to_csv('./data/bios_new.csv') 
# Save the File

In [14]:
# Lambda Function :-
bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x<165 else ('Average' if x<175 else "Tall") )
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [20]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 and row['weight_kg'] <= 80:
        return 'Middleweight'
    else:
        return 'HeavyWeigth'
bios['Category'] = bios.apply(categorize_athlete, axis = 1)
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,HeavyWeigth
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,HeavyWeigth

### Merging and Concatenationg Data ;-

In [36]:
nocs = pd.read_csv('./data/noc_regions.csv')

In [37]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [39]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [42]:
# Merge two data :-
bios_new = pd.merge(bios,nocs, left_on = 'born_country', right_on = 'NOC', how = 'left')
bios_new.rename(columns= {'region': 'full_country'}, inplace=True)
# inplace = True means change in Original DataSet
bios_new.head()
bios_new.drop(columns='notes',inplace=True)
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [44]:
ind = bios[bios['born_country'] == 'IND'].copy()
usa = bios[bios['born_country'] == 'USA'].copy()

In [45]:
# Concatenation :-
new_df = pd.concat([ind, usa])

In [46]:
new_df.head() # first all data is IND
new_df.tail() # Then joins data is USA

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [47]:
coffee.head()
total_sold = coffee['Units Sold'].sum()
coffee.loc[len(coffee),'Units Sold'] = total_sold

In [48]:
coffee.index
# coffee.drop(index=[ 16, 17,14],inplace=True)
# coffee.drop(index='Total',inplace=True)
coffee.rename(index={14 : 'Total_Sold'},inplace=True)

In [49]:
coffee

                  Day Coffee Type  Units Sold  Price  Revenue
0              Monday    Espresso        25.0   3.99    99.75
1              Monday        Maxx        15.0   5.99    89.85
2             Tuesday    Espresso        30.0   3.99   119.70
3             Tuesday       Latte        20.0   5.99   119.80
4           Wednesday    Espresso        35.0   3.99   139.65
5           Wednesday       Latte        25.0   5.99   149.75
6            Thursday    Espresso        40.0   3.99   159.60
7            Thursday       Latte        30.0   5.99   179.70
8              Friday    Espresso        45.0   3.99   179.55
9              Friday       Latte        35.0   5.99   209.65
10           Saturday    Espresso        45.0   3.99   179.55
11           Saturday       Latte        35.0   5.99   209.65
12             Sunday    Espresso        45.0   3.99   179.55
13             Sunday       Latte        35.0   5.99   209.65
Total_Sold        NaN         NaN       460.0    NaN      NaN

### handling Null Values :-

In [50]:
import numpy as np
coffee.loc[[0,1],'Units Sold'] = np.nan

In [51]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso         NaN   3.99    99.75
1     Monday        Maxx         NaN   5.99    89.85
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65

In [54]:
coffee.fillna(23.00).head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso        23.0   3.99    99.75
1     Monday        Maxx        23.0   5.99    89.85
2    Tuesday    Espresso        23.0   3.99   119.70
3    Tuesday       Latte        23.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65

In [55]:
coffee.loc[[0,1,2,3],'Units Sold'] = np.nan
coffee

                  Day Coffee Type  Units Sold  Price  Revenue
0              Monday    Espresso         NaN   3.99    99.75
1              Monday        Maxx         NaN   5.99    89.85
2             Tuesday    Espresso         NaN   3.99   119.70
3             Tuesday       Latte         NaN   5.99   119.80
4           Wednesday    Espresso        35.0   3.99   139.65
5           Wednesday       Latte        25.0   5.99   149.75
6            Thursday    Espresso        40.0   3.99   159.60
7            Thursday       Latte        30.0   5.99   179.70
8              Friday    Espresso        45.0   3.99   179.55
9              Friday       Latte        35.0   5.99   209.65
10           Saturday    Espresso        45.0   3.99   179.55
11           Saturday       Latte        35.0   5.99   209.65
12             Sunday    Espresso        45.0   3.99   179.55
13             Sunday       Latte        35.0   5.99   209.65
Total_Sold        NaN         NaN       460.0    NaN      NaN

In [58]:
coffee[coffee['Units Sold'].isna()] # rows contain null

       Day Coffee Type  Units Sold  Price  Revenue
0   Monday    Espresso         NaN   3.99    99.75
1   Monday        Maxx         NaN   5.99    89.85
2  Tuesday    Espresso         NaN   3.99   119.70
3  Tuesday       Latte         NaN   5.99   119.80

In [59]:
coffee.loc[[0],'Units Sold'] = 20

In [61]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()
# Put NAN value by using neighbour values
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso       20.00   3.99    99.75
1     Monday        Maxx       23.75   5.99    89.85
2    Tuesday    Espresso       27.50   3.99   119.70
3    Tuesday       Latte       31.25   5.99   119.80
4  Wednesday    Espresso       35.00   3.99   139.65

In [62]:
coffee.dropna() # remove NAN value rows

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso       20.00   3.99    99.75
1      Monday        Maxx       23.75   5.99    89.85
2     Tuesday    Espresso       27.50   3.99   119.70
3     Tuesday       Latte       31.25   5.99   119.80
4   Wednesday    Espresso       35.00   3.99   139.65
5   Wednesday       Latte       25.00   5.99   149.75
6    Thursday    Espresso       40.00   3.99   159.60
7    Thursday       Latte       30.00   5.99   179.70
8      Friday    Espresso       45.00   3.99   179.55
9      Friday       Latte       35.00   5.99   209.65
10   Saturday    Espresso       45.00   3.99   179.55
11   Saturday       Latte       35.00   5.99   209.65
12     Sunday    Espresso       45.00   3.99   179.55
13     Sunday       Latte       35.00   5.99   209.65

In [63]:
coffee

                  Day Coffee Type  Units Sold  Price  Revenue
0              Monday    Espresso       20.00   3.99    99.75
1              Monday        Maxx       23.75   5.99    89.85
2             Tuesday    Espresso       27.50   3.99   119.70
3             Tuesday       Latte       31.25   5.99   119.80
4           Wednesday    Espresso       35.00   3.99   139.65
5           Wednesday       Latte       25.00   5.99   149.75
6            Thursday    Espresso       40.00   3.99   159.60
7            Thursday       Latte       30.00   5.99   179.70
8              Friday    Espresso       45.00   3.99   179.55
9              Friday       Latte       35.00   5.99   209.65
10           Saturday    Espresso       45.00   3.99   179.55
11           Saturday       Latte       35.00   5.99   209.65
12             Sunday    Espresso       45.00   3.99   179.55
13             Sunday       Latte       35.00   5.99   209.65
Total_Sold        NaN         NaN      460.00    NaN      NaN

### Aggregating Data :-

In [143]:
bios[bios['born_country'] == 'USA']['born_region'].value_counts()
bios[bios['born_country'] == 'IND']['born_region'].value_counts().head()

born_region
Punjab           94
Maharashtra      56
West Bengal      49
Haryana          43
Uttar Pradesh    42
Name: count, dtype: int64

In [66]:
coffee.groupby(["Coffee Type"])['Units Sold'].sum()
coffee.groupby(['Coffee Type']).agg({'Units Sold':'sum'})

             Units Sold
Coffee Type
Espresso         257.50
Latte            191.25
Maxx              23.75

In [68]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name',ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

### Advance Functionality :-

In [69]:
coffee['yesterday_Units_Sold'] = coffee['Units Sold'].shift(2)
# shifted 2 row down

In [177]:
coffee['change_sold_percent'] = coffee['Units Sold'] / coffee['yesterday_Units_Sold'] * 100

In [70]:
# rank() :-
bios['height_rank'] = bios['height_cm'].rank()

In [ ]:
bios.sort_values(['height_rank'],ascending=False)

In [205]:
bios['height_rank'] = bios['height_cm'].rank(ascending=False)
bios_new = bios.sort_values(['height_rank'])
bios_new[['name','height_rank']]
# cumsum() = sum of rows by increase
# rolling(2) = add that count of values

                         name  height_rank
89070                Yao Ming          1.0
6978          Arvydas Sabonis          2.5
5781           Tommy Burleson          2.5
5673           Gunther Behnke          5.0
89075          Roberto Dueñas          5.0
...                       ...          ...
145490            Sin Ye-Chan          NaN
145491          Matthew Wepke          NaN
145492  Carlos García-Ordóñez          NaN
145493     Landysh Falyakhova          NaN
145499          Bill Phillips          NaN

[145500 rows x 2 columns]

### Done.....